-- Superstore Sales Analysis using SQL
-- Dataset: Superstore retail dataset
-- Objective: Analyze sales performance, regional trends, product performance, and profit by category.
-- Author: Akash Pariyar
-- Tool: MySQL Workbench

USE superstore_sales_analysis;

-- Inspect table structure
DESCRIBE superstore_sales;

-- Preview dataset
SELECT *
FROM superstore_sales
LIMIT 10;

-- Total company sales (overall revenue)
SELECT SUM(Sales) AS total_sales
FROM superstore_sales;

-- Sales performance by region
SELECT Region, SUM(Sales) AS total_sales
FROM superstore_sales
GROUP BY Region
ORDER BY total_sales DESC;

-- Top 10 products by total sales
SELECT `Product Name`, SUM(Sales) AS total_sales
FROM superstore_sales
GROUP BY `Product Name`
ORDER BY total_sales DESC
LIMIT 10;

-- Profit generated by each product category
SELECT Category, SUM(Profit) AS total_profit
FROM superstore_sales
GROUP BY Category
ORDER BY total_profit DESC;

-- Convert Order Date from text to proper date format
SELECT 
    STR_TO_DATE(`Order Date`, '%m/%d/%Y') AS order_date_fixed
FROM superstore_sales
LIMIT 10;

-- Monthly sales trend analysis
SELECT 
    DATE_FORMAT(STR_TO_DATE(`Order Date`, '%m/%d/%Y'), '%Y-%m') AS month,
    SUM(Sales) AS monthly_sales
FROM superstore_sales
GROUP BY month
ORDER BY month;

-- Running total of monthly sales using a window function
SELECT 
    DATE_FORMAT(STR_TO_DATE(`Order Date`, '%m/%d/%Y'), '%Y-%m') AS month,
    SUM(Sales) AS monthly_sales,
    SUM(SUM(Sales)) OVER (ORDER BY DATE_FORMAT(STR_TO_DATE(`Order Date`, '%m/%d/%Y'), '%Y-%m')) AS running_total_sales
FROM superstore_sales
GROUP BY month
ORDER BY month;
